# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Engineered Eloquence   
tagline:             Read, Think, Share, Repeat
url:                 https://engineeredeloquence.com
paginate:            1
baseurl:             "https://thejayray.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jay Ray
  url:               https://twitter.com/jayray
  email:             jayray@engineeredeloquence.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/thejayray/thejayray.github.io
