# Site settings
title: "Jay Ray - Online Resume"
description: "An online resume for Jay Ray, Technology Manager"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jay Ray"
resume_title:                   "Technology Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jayray@engineeredeloquence.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "773-517-8846"
#resume_contact_address:         ""

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Jay Ray has spent his entire career in higher education technology across the non-profit sector, proprietary education, and public and private institutions, specifically focusing on help desk support and management, infrastructure design and implementation.<br>In 2014, Jay took over as Technology Operations Manager for the Libraries at University of Wisconsin-Madison, where he manages services across multiple campus libraries. College Library and its sister libraries provide services to the general student population that include the lending of technology assets for short-term use (gaming consoles, iPads, dual-boot Mac laptops, cameras, and more); access to cutting-edge computing and printing solutions; and access to multiple computer labs and reservable study spaces. In addition, College Library houses one of the campuses Wisconsin Collaboratory for Enhanced Learning (WisCEL) centers, which provides a multipurpose computer lab for active learning, blended, or flipped classroom instruction during the weekday and computing resources at night.<br>Jay has spearheaded programs to ensure that the libraries remain in sight of what students and faculty on campus need and want out of their educational institution's library facilities. Most recently, Jay has written for EdTech Magazine on iPad circulation and was published in the SIGUCCS 2017 Conference Journal, writing about the pilot process framework formulated at and utilized by College Library in trying out new and interesting technologies.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
#resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/thejayray/"
  resume_twitter_url:           "http://twitter.com/jayray"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/thejayray"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://engineeredeloquence.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
