# Setup
title:               Engineered Eloquence
url:                 https://engineeredeloquence.com
tagline:             "Minimalism, Technology, and Parenthood"
paginate:            1
baseurl:             "/"
markdown:            kramdown

# About/contact
author: Jay Ray
author:
  name: Jay Ray
  email: jayray@engineeredeloquence.com
email: jayray@engineeredeloquence.com
description: > # description of the site (multiple lines allowed)
  Minimalism, Technology, and Parenthood

# Permalinks
permalink: /:year/:month/:title

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
svg: "logo.svg"

# Theme Info
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "< &#9820;" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Other
timezone:            America/Chicago

# Custom vars
version:             7.0.0
github:              https://github.com/thejayray/
repo:                https://github.com/thejayray/thejayray.github.io