# Permalinks
permalink:           /:year/:month/:title/

# Setup
title:               Engineered Eloquence
url:                 https://engineeredeloquence.com
paginate:            1
baseurl:             "https://engineeredeloquence.com"

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jay Ray
  url:               https://twitter.com/jayray
  email:             jayray@engineeredeloquence.com

# Other
timezone:            America/Chicago

# Custom vars
version:             4.0.0
github:              https://github.com/thejayray/
repo:                https://github.com/thejayray/thejayray.github.io